apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: jizt-cluster
  namespace: kafka
  labels:
    app: jizt
    chart: jizt-0.0.1
    release: "jizt"
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: false
      log.message.format.version: 2.6-IV0
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
