####################################
# Kubernetes related configuration #
####################################

# Ingress configuration
# ref: http://kubernetes.io/docs/user-guide/ingress/
ingress:
  hostname: "api.jizt.it"
  paths:
    v1: "/v1/summaries"

# General replica count for ALL the deployments
replicaCount: 1

# Autoscaling configuration
# ref: https://kubernetes.io/blog/2016/07/autoscaling-in-kubernetes/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Configuration for the Dispatcher microservice
dispatcher:
  name: "dispatcher"
  ports:
    svc: 5000
    container: 5000
  image: jizt/dispatcher:0.0.4

# Configuration for the Text Preprocessor microservice
textPreprocessor:
  name: "text-preprocessor"
  ports:
    svc: 5000
    container: 5000
  image: jizt/text-preprocessor:0.0.2


###############################
# Kafka related configuration #
###############################

# Global configuration for Strimzi
strimzi:
  namespace: "strimzi"  # must exist beforehand in the Kubernetes cluster

# Configuration for Strimzi Kafka cluster
# ref: https://strimzi.io/docs/operators/master/using.html#proc-config-kafka-str
kafka:
  name: "jizt-kafka-cluster"
  version: 2.7.0
  replicas: 1
  resources:
    memoryRequests: 1Gi
    memoryLimits: 1Gi
  config:
    autoCreateTopics: "false"
    messageMaxBytes: 1048588  # 1 MiB
    topicReplicationFactor: 1
    logReplicationFactor: 1
    logMinIsr: 1
    logMessageFormatVersion: "2.7-IV2"
  zookeeper:
    replicas: 1

# Global configuration for Kafka topics
# ref: https://strimzi.io/docs/operators/master/using.html#type-KafkaTopic-reference
topics:
  partitions: 1
  replicas: 1
  retentionMs: 600000  # 10 minutes
