# Template for jizt Kafka topics.
# All keys with values "{}" must be overriden
# with specific values.
{{- define "jiztlibchart.kafka-topic.tpl" -}}
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {}
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: "{{ $.Release.Name }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  partitions: {{ .Values.topics.partitions }}
  replicas: {{ .Values.topics.replicas }}
  config:
    retention.ms: {{ .Values.topics.retentionMs }}
{{- end -}}


{{- define "jiztlibchart.kafka-topic" -}}
{{- include "jiztlibchart.util.merge" (append . "jiztlibchart.kafka-topic.tpl") -}}
{{- end -}}