apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.modelsStorageClass.name }}
provisioner: pd.csi.storage.gke.io
volumeBindingMode: {{ .Values.modelsStorageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.modelsStorageClass.allowVolumeExpansion }}
parameters:
  type: pd-balanced