{{- include "jiztlibchart.deployment" (list . "jizt.dispatcher-deployment") -}}
{{- define "jizt.dispatcher-deployment" -}}
metadata:
  name: {{ .Values.dispatcher.name }}-deployment
  labels:
    microservice: {{ .Values.dispatcher.name }}
spec:
  selector:
    matchLabels:
      microservice: {{ .Values.dispatcher.name }}
  template:
    metadata:
      labels:
        microservice: {{ .Values.dispatcher.name }}
    spec:
      containers:
      - name: {{ .Values.dispatcher.name }}
        image: {{ .Values.dispatcher.image }}
        ports:
        - containerPort: {{ .Values.dispatcher.ports.container }}
{{- end -}}