apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "jizt.name" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: {{ $.Release.Name }}
spec:
  rules:
  #- host: {{ .Values.ingress.hostname }}
  - http:
      paths:
        - path: {{ .Values.ingress.paths.v1 }} 
          pathType: Prefix
          backend:
            serviceName: {{ .Values.dispatcher.name }}-service
            servicePort: {{ .Values.dispatcher.ports.svc }}