apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: "{{ $.Release.Name }}"
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    resources:
      requests:
        memory:
      limits:
        memory:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: {{ .Values.kafka.config.autoCreateTopics }}
      offsets.topic.replication.factor: {{ .Values.kafka.config.topicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.logReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.logMinIsr }}
      log.message.format.version: {{ .Values.kafka.config.logMessageFormatVersion }}
      log.retention.ms: {{ .Values.kafka.config.logRetentionMs }}
    storage:
      type: ephemeral
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicas }}
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}