apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.modelsPV.name }}-pvc
  labels:
    app: {{ include "jizt.name" . }}
    chart: {{ include "jizt.chart" . }}
    release: "{{ $.Release.Name }}" }}
spec:
  accessModes:
  - {{ .Values.modelsPV.acessModes.rom }}
  resources:
    requests:
      storage: {{ .Values.modelsPV.capacity.storage }}