name: Build & Publish Sphinx docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Sphinx docs
      uses: sphinx-notes/pages@master
      with:
        documentation_path: docs/sphinx
        install_requirements: true 
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        deploy_key: ${{ secrets.ACTIONS_BUILD_DOCS_KEY }}
        force_orphan: true
