name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: jizt-med-cluster-3
  GKE_ZONE: europe-west2-a
  RELEASE_NAME: jizt
  HELM_PATH: src/helm/jizt

jobs:
  deploy:
    name: Deploy JIZT
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}
        
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_KEY }}
    
    - name: Delete previous deployments
      run: >-
        kubectl delete deploy
          dispatcher-deployment
          text-preprocessing-deployment
          t5-large-text-encoding-deployment
          t5-large-text-summarization-deployment
          text-postprocessing-deployment

    - name: Upgrade JIZT
      run: >-
        helm upgrade ${{ env.RELEASE_NAME }} ${{ env.HELM_PATH }}
